OPENTOK-44681: add dtx functionality to meet
opentok/opentok-meet pull request #136
Opened 2021-09-03 00:54 UTC by michaelwhittemore

#### What is this PR doing?
Right now the dtx checkmark on the meet landing page doesn't actually do anything. This PR should add dtx functionality. 
We also need to update meet to use a version of OT that has the dtx PR before this will work. 

#### How should this be manually tested?
1. Run meet locally and select dtx. 
2. Verify that `usedtx=1` is appearing in both the local offer and remote answer via the verbose console log. 
3. Run meet locally and make sure dtx is unselected.  
2. Verify that `usedtx=1` is not appearing in both the local offer and remote answer via the verbose console log. 

#### What are the relevant tickets?
https://jira.vonage.com/browse/OPENTOK-44681

2021-09-03 01:15 UTC, v-kpheng approved these changes
LGTM! 🚀 💪

2021-09-03 01:15 UTC, v-kpheng commented on src/js/controllers.js
> +    $scope.enableDtx = url.searchParams.get('dtx');
Can this be a local variable instead, e.g., `const enableDtx = foo`?

2021-09-03 01:42 UTC, michaelwhittemore commented on src/js/controllers.js
> +    $scope.enableDtx = url.searchParams.get('dtx');
Sure, will do. I guess room.ejs doesn't need to access it as it's being bundled into the face properties

2021-09-03 01:51 UTC, v-kpheng approved these changes
LGTM! 🚀 💪

2021-09-06 15:36 UTC, ggoldens requested changes
Thanks @michaelwhittemore, please review my comments. Thanks!!

2021-09-06 15:36 UTC, ggoldens commented on src/js/controllers.js
> +    const enableDtx = url.searchParams.get('dtx');
The manual test didn't pass on my end. I think `url.searchParams.get('dtx')` will return a string, like 'true', and since 'true' is not a boolean, it's turned to false.

2021-09-06 15:40 UTC, ggoldens commented on src/js/controllers.js
> +    const enableDtx = url.searchParams.get('dtx');
I just pushed the change, and now it's working. Sorry for doing this on your PR, just wanted to unblock this since it's holiday on US.

2021-09-06 15:40 UTC, ggoldens approved these changes
After my PR I see it's working.

2021-09-06 15:41 UTC, merged

2021-09-07 18:03 UTC, michaelwhittemore commented on src/js/controllers.js
> +    const enableDtx = url.searchParams.get('dtx');
Thanks for taking the initiative!