OPENTOK-46538: Remove old anvil end point on meet
opentok/opentok-meet pull request #152
Opened 2022-03-08 01:55 UTC by michaelwhittemore

#### What is this PR doing?
https://opentok-meet.herokuapp.com/ is making a lot of requests to anvil that are 404ing. See https://vonage.slack.com/archives/CCX1CLQKV/p1645719021635629 & https://vonage.slack.com/archives/CCY5ZBC6T/p1645737904105019 for more context. Apparently this has been happening for a while but was only recently discovered.

Kongpheng and traced this to https://github.com/opentok/opentok-meet/blob/master/plugins/anvil.js which had a subscriber stats report added 6 years ago. As this isn't returning anything useful and is causing problems for the anvil team it is being removed. 

#### How should this be manually tested?

#### What are the relevant tickets?
https://jira.vonage.com/browse/OPENTOK-46538

2022-03-08 16:05 UTC, albertoacn requested changes
I don't think we should remove this. I would suggest to enable/disable the feature based on the environment.

2022-03-08 16:05 UTC, albertoacn commented on plugins/subscriber-info/index.js
> +    res.send('This endpoint is no longer supported');
@michaelwhittemore we are using this path to retrieve the streamId for the subscriber stats panel: https://github.com/opentok/opentok-meet/blob/master/src/js/subscriber-stats.js#L92
This is used by different teams to triage problems on the subscriber leg for a specific stream.

2022-03-08 23:16 UTC, michaelwhittemore commented on plugins/subscriber-info/index.js
> +    res.send('This endpoint is no longer supported');
Thanks for finding that, I wasn't sure where the request was being made from. I couldn't find this line and assumed it was so internal tool. Regardless, the anvil end point is still not supported on production. If you start a session in  https://opentok-meet.herokuapp.com/ with a subscriber you'll see the console log is filled with anvil 404 errors 
<img width="766" alt="Screen Shot 2022-03-08 at 3 15 33 PM" src="https://user-images.githubusercontent.com/35385066/157341939-f71e5a75-dc31-4e6c-b10c-2ccfb9cc60f3.png">

Because the endpoint doesn't actually return any useful information I still think it should be removed. What do you think @albertoacn & @v-kpheng?

2022-03-08 23:20 UTC, v-kpheng commented on plugins/subscriber-info/index.js
> +    res.send('This endpoint is no longer supported');
@michaelwhittemore, can you enable this only on dev, like Alberto suggested?  That way, prod would be spammed with invalid requests?

2022-03-09 23:27 UTC, michaelwhittemore commented
> I don't think we should remove this. I would suggest to enable/disable the feature based on the environment.

@albertoacn & @v-kpheng. Based on your feedback I'm only ignoring this end point on prod. Please review when you get a chance

2022-03-10 03:06 UTC, v-kpheng approved these changes
LGTM! 💪 🚀

2022-03-10 03:06 UTC, v-kpheng commented on src/js/subscriber-stats.js
> +        if (OT.properties.apiURL !== 'https://anvil.opentok.com') {
How do you feel about making this less restrictive?  For example, if the API URL contains `anvil.opentok.com`, then we assume it's prod.

2022-03-14 12:18 UTC, albertoacn approved these changes
LGTM

2022-03-15 18:41 UTC, behei-vonage approved these changes
🚀

2022-04-04 16:10 UTC, maikthomas commented on plugins/subscriber-info/index.js
> +    res.send('This endpoint is no longer supported');
Just to clarify on the above information: 
streamID is provided by the subscriber directly.
These are the two fields populated by this endpoint:
- originServer
- edgeServer

2022-04-04 16:13 UTC, maikthomas commented
I have tested this using Dev and Prod.
I can confirm that for
Dev:
- We are still using the endpoint
- streamId is shown as expected
- Origin server & Edge server shown as expected

Prod:
- We are no longer using the endpoint (no 404s)
- streamId shown as expected
- origin/edge servers _not_ shown. 

LGTM ✅

2022-04-04 16:13 UTC, maikthomas approved these changes

2022-04-04 22:24 UTC, merged